"type: mapping":
  - changed-files:
      - any-glob-to-any-file:
          - "Resources/Maps/**/*.yml"
          - "Resources/Prototypes/Maps/**/*.yml"

"type: documentation":
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**"
          - "Documentation/**"

"type: localization":
  - changed-files:
      - any-glob-to-any-file:
          - "Resources/Locale/**"
          - "**/*.ftl"

"type: test":
  - changed-files:
      - any-glob-to-any-file:
          - "Content.Tests/**"
          - "Content.IntegrationTests/**"
          - "**/*Tests.cs"
          - "**/*Test.cs"

"Changes: No C#":
  - changed-files:
      - all-globs-to-all-files:
          - "!**/*.cs"
