using Content.Shared.EntityStore;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._InfiniteAegis.EntityStore;

[GenerateTypedNameReferences]
public sealed partial class EntityStoreMenu : DefaultWindow
{
    public event Action<string>? OnBuyOffer;

    public EntityStoreMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(EntityStoreBoundUserInterfaceState state)
    {
        BalanceLabel.Text = Loc.GetString("entity-store-balance", ("amount", state.Balance));
        OffersContainer.Children.Clear();

        foreach (var offer in state.Offers)
        {
            var control = new EntityStoreOfferControl(offer);
            control.OnBuy += () => OnBuyOffer?.Invoke(offer.Id);
            OffersContainer.AddChild(control);
        }
    }
}
