using Content.Shared.Garage;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._InfiniteAegis.Garage;

[GenerateTypedNameReferences]
public sealed partial class GarageMenu : DefaultWindow
{
    public event Action<Guid>? OnCall;

    public GarageMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(GarageBoundUserInterfaceState state)
    {
        VehiclesContainer.Children.Clear();

        foreach (var vehicle in state.Vehicles)
        {
            var control = new GarageVehicleControl(vehicle);
            control.OnCall += () => OnCall?.Invoke(vehicle.Id);
            VehiclesContainer.AddChild(control);
        }
    }
}
