using Content.Shared.Garage;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._InfiniteAegis.Garage;

[GenerateTypedNameReferences]
public sealed partial class GarageVehicleControl : Control
{
    [Dependency] private IEntityManager _entities = default!;
    [Dependency] private IPrototypeManager _prototypes = default!;

    public event Action? OnCall;

    public GarageVehicleControl(GarageVehicleData vehicle)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        if (_prototypes.TryIndex<EntityPrototype>(vehicle.PrototypeId, out var prototype))
        {
            NameLabel.Text = prototype.Name;
            Icon.Texture = _entities.System<SpriteSystem>().GetPrototypeIcon(prototype.ID).Default;
        }
        else
        {
            NameLabel.Text = vehicle.PrototypeId;
        }

        CallButton.Text = Loc.GetString("garage-call");
        CallButton.OnButtonDown += _ =>
        {
            CallButton.Disabled = true;
            OnCall?.Invoke();
        };
    }
}
