blank_issues_enabled: false
contact_links:
  - name: Предложить идею
    url: https://discord.gg/t8XAuymcDs
    about: Обсуждение новых механик, контента и изменений проходит в Discord Infinite Aegis.

  - name: Получить помощь
    url: https://discord.gg/t8XAuymcDs
    about: Задайте вопрос участникам и разработчикам проекта.
