using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._InfiniteAegis.Vehicle;

[GenerateTypedNameReferences]
public sealed partial class VehicleHud : PanelContainer
{
    public VehicleHud()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateValues(float speed, int durability, FixedPoint2 fuel, FixedPoint2 maximumFuel, int gear)
    {
        SpeedValue.Text = Loc.GetString("vehicle-hud-speed-value", ("speed", speed.ToString("0.0")));
        DurabilityValue.Text = Loc.GetString("vehicle-hud-durability-value", ("durability", durability));
        FuelValue.Text = Loc.GetString("vehicle-hud-fuel-value", ("fuel", fuel), ("maximumFuel", maximumFuel));
        GearValue.Text = gear.ToString();
    }
}
