using System.Numerics;
using System.Linq;
using Content.Shared.Venicle;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._InfiniteAegis.Venicle;

[GenerateTypedNameReferences]
public sealed partial class VenicleSeatMenu : DefaultWindow
{
    private const float MapSize = 380f;
    private const float SeatControlWidth = 120f;
    private const float SeatControlHeight = 96f;
    private const float SeatSquareCenterY = 48f;

    public event Action<string>? OnChangeSeat;
    public event Action<NetEntity>? OnKick;

    public VenicleSeatMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(VenicleBoundUserInterfaceState state)
    {
        SeatMap.Children.Clear();
        if (state.Seats.Count == 0)
            return;

        var maximumOffset = state.Seats.Max(seat =>
            MathF.Max(MathF.Abs(seat.Offset.X), MathF.Abs(seat.Offset.Y)));
        var scale = maximumOffset > 0f ? 130f / maximumOffset : 1f;
        var mapCenter = new Vector2(MapSize / 2f, MapSize / 2f);

        foreach (var seat in state.Seats)
        {
            var control = CreateSeatControl(seat);
            SeatMap.AddChild(control);

            var squareCenter = mapCenter + seat.Offset * scale;
            LayoutContainer.SetPosition(control, new Vector2(
                squareCenter.X - SeatControlWidth / 2f,
                squareCenter.Y - SeatSquareCenterY));
        }
    }

    private BoxContainer CreateSeatControl(VenicleSeatUiData seat)
    {
        var root = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            MinSize = new Vector2(SeatControlWidth, SeatControlHeight),
            MaxSize = new Vector2(SeatControlWidth, SeatControlHeight),
        };

        root.AddChild(new Label
        {
            Text = seat.OccupantName ?? string.Empty,
            Align = Label.AlignMode.Center,
            ClipText = true,
            MinSize = new Vector2(SeatControlWidth, 20f),
            MaxSize = new Vector2(SeatControlWidth, 20f),
        });

        var seatButton = new Button
        {
            Text = seat.Occupant != null ? "●" : string.Empty,
            Disabled = seat.Occupant != null,
            HorizontalAlignment = HAlignment.Center,
            MinSize = new Vector2(56f, 56f),
            MaxSize = new Vector2(56f, 56f),
            ToolTip = seat.Driver ? Loc.GetString("venicle-driver-seat") : Loc.GetString("venicle-change-seat"),
        };
        seatButton.OnPressed += _ => OnChangeSeat?.Invoke(seat.Id);
        root.AddChild(seatButton);

        var kickButton = new Button
        {
            Text = Loc.GetString("venicle-kick"),
            Visible = seat.Occupant != null,
            HorizontalAlignment = HAlignment.Center,
            MinSize = new Vector2(88f, 20f),
        };

        if (seat.Occupant is { } occupant)
            kickButton.OnPressed += _ => OnKick?.Invoke(occupant);

        root.AddChild(kickButton);
        return root;
    }
}
