using Content.Shared.CarDealerStore;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._InfiniteAegis.CarDealerStore;

[GenerateTypedNameReferences]
public sealed partial class CarDealerStoreMenu : DefaultWindow
{
    public event Action<string>? OnBuyOffer;

    public CarDealerStoreMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(CarDealerStoreBoundUserInterfaceState state)
    {
        BalanceLabel.Text = Loc.GetString("car-dealer-store-balance", ("amount", state.Balance));
        OffersContainer.Children.Clear();

        foreach (var offer in state.Offers)
        {
            var control = new CarDealerStoreOfferControl(offer);
            control.OnBuy += () => OnBuyOffer?.Invoke(offer.Id);
            OffersContainer.AddChild(control);
        }
    }
}
