using Content.Shared.CarDealerStore;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._InfiniteAegis.CarDealerStore;

[GenerateTypedNameReferences]
public sealed partial class CarDealerStoreOfferControl : Control
{
    [Dependency] private IEntityManager _entities = default!;
    [Dependency] private IPrototypeManager _prototypes = default!;

    public event Action? OnBuy;

    public CarDealerStoreOfferControl(CarDealerStoreOfferData offer)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        if (_prototypes.TryIndex<EntityPrototype>(offer.ProductEntity, out var prototype))
        {
            NameLabel.Text = prototype.Name;
            Icon.Texture = _entities.System<SpriteSystem>().GetPrototypeIcon(prototype.ID).Default;
            DescriptionLabel.SetMessage(FormattedMessage.FromUnformatted(
                string.IsNullOrWhiteSpace(offer.DescriptionLoc)
                    ? prototype.Description
                    : Loc.GetString(offer.DescriptionLoc)));
        }
        else
        {
            NameLabel.Text = offer.ProductEntity;
            DescriptionLabel.SetMessage(FormattedMessage.FromUnformatted(offer.DescriptionLoc ?? string.Empty));
        }

        BuyButton.Text = offer.Price == 0
            ? Loc.GetString("car-dealer-store-free")
            : Loc.GetString("car-dealer-store-price", ("price", offer.Price));
        BuyButton.OnButtonDown += _ =>
        {
            BuyButton.Disabled = true;
            OnBuy?.Invoke();
        };
    }
}
